const albums = [
    {
        id: '1',
        title: 'MAIDEN STAKEHOLDER CONFERENCE 2022',
        date: '13th Dec 2022 ',
        nn: [
            
            'images/gallery/stakeholder_conference_2022/SJR_3654.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3664.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3710.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3665.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3715.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3719.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3744.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3749.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3709.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3751.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3753.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3755.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3698.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3761.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3763.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3767.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3770.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3780.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3785.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3789.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3790.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3791.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3796.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3797.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3801.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3802.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3803.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3808.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3809.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3812.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3821.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3823.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3830.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3834.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3838.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3840.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3842.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3844.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3846.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3893.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3897.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3899.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3918.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3925.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3927.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3931.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3933.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3936.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3941.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3943.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3948.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3951.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3969.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3970.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3972.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3978.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3979.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3980.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3982.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3984.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3990.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3994.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_3999.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4002.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4005.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4012.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4017.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4030.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4034.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4040.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4045.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4052.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4072.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4088.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4092.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4096.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4101.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4105.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4112.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4114.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4116.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4118.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4120.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4140.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4142.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4144.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4173.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4204.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4218.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4226.jpg',
               'images/gallery/stakeholder_conference_2022/SJR_4230.jpg',
        ]

    },
    {
        id: '2',
        title: 'COURTESY CALL TO GHANA STATISTICAL SERVICE',
        date: '19th May 2022',
        nn: [
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
        ]
    },

    {
        id: '3',
        title: ' COURTESY CALL TO GHANA Revenue Authority',
        date: '2nd June 2022',
        nn: [
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
        ]
    },
    {
        id: '4',
        title: 'ASSOCIATION OF GHANA INDUSTRIES COURTESY CALL TO GITC',
        date: '27th May 2022',
        nn: [
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
        ]
    },
    {
        id: '5',
        title: 'HON.DEPUTY MINISTER (TRADE) COURTESY CALL TO GITC',
        date: '19th May 2022',
        nn: [
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
        ]
    },
    {
        id: '6',
        title: 'TRAINING SESSION WITH BMWK',
        date: '19th - 29th April 2022',
        nn: [
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
        ]
    },
    {
        id: '7',
        title: 'GITC RETREAT WITH STAFF,TECHNICAL COMMITTEE AND GOVERNING BOARD',
        date: '17th - 18th March 2022',
        nn: [
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
            'images/publish/publish.jpg',
        ]
    },
]

export default albums;